### ISSUE TITLE
Création d'un index.php qui sera notre contrôleur frontal

### ISSUE THREAD

**Issue by mikhawa** [WebDevCF2m2020/git2revision#2]
Création d'un index.php qui sera notre contrôleur frontal: Il est vide pour le moment, à part l'ouverture et fermeture de php

**Comment by mikhawa** [comment]
Qui veut le faire?

**Comment by CHIHAB09** [comment]
yes

**Comment by Jess2403** [comment]
moi je veux bien

**Comment by karimtouami** [comment]
Yes

**Comment by mikhawa** [comment]
Je l'ai fait

**Comment by Jess2403** [comment]
apparement tu ne reçois pas ce que je t'envoie car je t'ai envoyé un fichier .gitignore
