### ISSUE TITLE
Moi aussi je veux créer de nouvelles issues

### ISSUE THREAD

**Issue by wawatusee** [WebDevCF2m2020/git2revision#4]
Créer des issues pour rien dire, c'est pas productif

**Comment by mikhawa** [comment]
tu peux, mais non lié à un ticket, il s'agit d'une proposition ou une conversation

**Comment by crhubhub** [comment]
ok 👍

**Comment by servietskyCF2M** [comment]
test

**Comment by alain17-web** [comment]
blablabla

**Comment by ghost** [comment]
Tout à fait d'accord

**Comment by CHIHAB09** [comment]
;)

**Comment by LaInca** [comment]
Hello...

**Comment by wawatusee** [comment]
Ben par exemple, je veux bien faire une css, là c'est une vrai proposition? Non?
